# Generated by Django 5.2.14 on 2026-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('material', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
